# Generated by Django 4.1.6 on 2023-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='input_taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.CharField(max_length=30)),
                ('user_linkname', models.CharField(max_length=300)),
            ],
        ),
    ]
